# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 0.7
  - 1.0
  - nightly
notifications:
  email: false
matrix:
  allow_failures:
    - julia: nightly
after_success:
    - |
        julia -e '
          import LocalScopeBenchmarks, Pkg
          Pkg.add("Coverage")
          using Coverage
          cd(normpath(dirname(pathof(LocalScopeBenchmarks)), ".."))
          Codecov.submit(process_folder())
        '
